/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.jz423.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintStream;
import java.io.Reader;
import java.io.StringReader;
import java.io.InputStreamReader;

public class App {
  TextPlayer player1;
  TextPlayer player2;
  
  public App(TextPlayer p1, TextPlayer p2) {
    this.player1 = p1;
    this.player2 = p2;
  }

  /**
   * It is a function that reads Placement from the input String on system.
   * 
   * @param prompt: Words that asks user to input string.
   * @return return a Placement
   */
  public Placement readPlacement(String prompt) throws IOException {
    out.println(prompt);
    String s = inputReader.readLine();
    return new Placement(s);
  }

  /**
   * It is a function that place one ship to a board based on system in, and it
   * will print out
   * the board
   */
  public void doOnePlacement() throws IOException {
    Placement place = readPlacement("Where would you like to put your ship?");
    Ship<Character> ship = shipFactory.makeDestroyer(place);

    // BasicShip ship = new BasicShip(place.getWhere());
    theBoard.tryAddShip(ship);
    out.println(view.displayMyOwnBoard());
  }

  public void doPlacementPhase() throws IOException {
    player1.doOnePlacement();
  }

  public static void main(String[] args) throws IOException {
    // Board<Character> b = new BattleShipBoard<>(10, 20);
    // App app = new App(b, new InputStreamReader(System.in), System.out);
    // app.doOnePlacement();

    Board<Character> b1 = new BattleShipBoard<Character>(10, 20);
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20);
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    V1ShipFactory factory = new V1ShipFactory();

    TextPlayer p1 = new TextPlayer("A", b1, input, System.out, factory);
    TextPlayer p2 = new TextPlayer("B", b2, input, System.out, factory);
    App app = new App(p1, p2);
    app.doPlacementPhase();
  }

}
